# Generated by Django 5.2.6 on 2025-10-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='preparacion',
            new_name='instrucciones',
        ),
    ]
